### ISSUE TITLE
Is this thing on?

### ISSUE THREAD

**Issue by felix91gr** [Lemmih/lhc#2]
Hi! I’m interested in this project. I think it’s healthy for a language to have a compiler developed for it that actually uses LLVM.

LLVM allows for performant code. _Very performant_. And with good static analysis as well.

I want this project to exist. I don’t have much to give in return (yet), but I wanna know if it will exist for the day I bring something :)

**Comment by Lemmih** [comment]
It's on. :)

I'm writing a reusable name resolution library and type-checking library as part of the haskell-suite. Once those are done, I can continue on LHC. Unfortunately I don't have much time.

This project might be of interest to you: https://github.com/ollef/sixten

**Comment by Lemmih** [comment]
Development has continued on LHC. Closing this issue.
